description: |
    This config file is designed to run rna pipeline.

author: "Jocelyn Brayet"

samples:
    SAMPLES_TAB_FILE: "/bioinfo/users/jbrayet/Bureau/snakemake/pipeline_rna/samples.tab"

group:
    R1: "R1"
    R2: "R2"

general_path:
    INPUT_PATH: "/data/tmp/TEST_SNAKEMAKE"
    OUTPUT_PATH: "/data/tmp/TEST_SNAKEMAKE/results_star_htseq"
    RULE_PATH: "/bioinfo/users/jbrayet/Bureau/snakemake/snakemake_rules"
    SCRIPT_PATH: "/bioinfo/users/jbrayet/snakemake/alban_scripts/"

graph:
    SNAKEFILE: "/bioinfo/users/jbrayet/Bureau/snakemake/pipeline_rna/snakefile_rna_pipeline"
    DOT_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/bin/"

fastqc:
    FASTQC_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/FastQC/"

trim_galore:
    CUTADAPT_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/bin/"
    TRIMGALORE_BIN_DIR: "/bioinfo/local/build/trim_galore_v0.4.0/"

aligment:
    TOOL: "STAR"     # STAR or TOPHAT2

tophat2:
    TOPHAT2_BIN_DIR: "~/miniconda3/envs/alban_env/bin/"
    RG_LIBRARY: "Illumina"
    BOWTIE2_REFERENCE_ROOT: "/data/annotations/Galaxy/Mouse/mm10/bowtie2/mm10"
    MAXHITS: "1"
    MM_RNA: "3"
    INSERTSIZE: "150"
    ECART_TYPE: "80"
    GTF_FILE: "/data/annotations/Galaxy/RefGene/mm10/mm10_refGene.gtf"
    G_OPTION: "1"
    RNA_LIBRARY_TYPE: "fr-firststrand"

htseq:
    HTSEQ_BIN_DIR: "~/miniconda3/envs/py27/bin/"
    STRANDED: "'no'"
    SAM_TYPE: "bam"
    ORDER: "name"
    GTF_FILE: "/data/tmp/TEST_SNAKEMAKE/refFlat.gtf"

star:
    STAR_BIN_DIR: "/bioinfo/local/build/STAR/STAR_2.5.0a/bin/Linux_x86_64/"
    GENOME_FASTA_FILE: "/data/annotations/Mouse/mm10/complete/STAR_indexes/"
    RUN_THREADN: "8"
    OUT_SAM_TYPE: "BAM SortedByCoordinate"
    RUN_MODE: "alignReads"
    GENOME_DIR: "/data/annotations/star_indexes/mm10"
    SJDB_GTF_FILE: "/bioinfo/users/jbrayet/Bureau/starAnnotations/Mus_musculus.GRCm38.84.gtf"
    SJDB_OVERHANG: "100"
    OUT_FILTER_MULTIMAP_NMAX: "1"
    OUT_READS_UNMAPPED: "Fastx"
    OUT_FILTER_MISMATCH_NMAX: "6"
    READ_FILES_COMMAND: "zcat"
    QUANT_MODE: "GeneCounts"
    OUT_SAM_STRAND_FIELD: "intronMotif"
    LB: "Illumina"

gatk:
    GATK_BIN_DIR: "/bioinfo/local/build/GATK/GenomeAnalysisTK-2.2-16-g9f648cb/"
    BED_FILE: ""
#    FASTA_REFERENCE: "/bioinfo/users/jbrayet/Bureau/starAnnotations/Mus_musculus.GRCm38.dna.alt.fa"
    FASTA_REFERENCE: "/data/annotations/Galaxy/Mouse/mm10/bowtie2/mm10.fa"

samtools:
    SAMTOOLS_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/bin/"
#    FASTA_REFERENCE: "/bioinfo/users/jbrayet/Bureau/starAnnotations/Mus_musculus.GRCm38.dna.alt.fa"
    FASTA_REFERENCE: "/data/annotations/Galaxy/Mouse/mm10/bowtie2/mm10.fa"

picard:
    MARKDUP: "no"
    PICARD_TOOLS_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/bin/"

bedtools:
    BEDTOOLS_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/bin/"

curie_report:
    LIBRARY_DONE_BY: "Alban"
    SEQUENCING_DONE_BY: "Jocelyn"
    PROJECT_LEADER: "Jocelyn"
    RUN_DATE: "25-04-2016"
    SPECIES: "Mouse"
    SPECIES_BUILD: "mm10"
    READ_LENGTH: "100"
    MARKDUP: "yes"


