description: |
    This config file is designed to run rna pipeline.

author: "Jocelyn Brayet"

samples:
    B99T1: "B99T1"
    B99T2: "B99T2"

biosamples:
    biosample1: "biosample1"
    biosample2: "biosample2"

group:
    R1: "R1"
    R2: "R2"

general_path:
    INPUT_PATH: "/bioinfo/users/jbrayet/snakemake/input_rna_pipeline"
    OUTPUT_PATH: "/bioinfo/users/jbrayet/snakemake/pasteur_temp_files"
    RULE_PATH: "/bioinfo/users/jbrayet/Bureau/snakemake/snakemake_rules"
    SCRIPT_PATH: "/bioinfo/users/jbrayet/snakemake/alban_scripts/"

graph:
    SNAKEFILE: "/bioinfo/users/jbrayet/Bureau/snakemake/pipeline_rna/snakefile_rna_pipeline"
    DOT_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/bin/"

fastqc:
    FASTQC_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/FastQC/"

trim_galore:
    CUTADAPT_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/bin/"
    TRIMGALORE_BIN_DIR: "/bioinfo/local/build/trim_galore_v0.4.0/"

aligment:
    TOOL: "TOPHAT2"

tophat2:
    TOPHAT2_BIN_DIR: "~/miniconda3/envs/py27/bin/"
    RG_LIBRARY: "Illumina"
    BOWTIE2_REFERENCE_ROOT: "/data/annotations/Mouse/mm10/complete/bowtie2_indexes/mm10"
    MAXHITS: "1"
    MM_RNA: "3"
    INSERTSIZE: "150"
    ECART_TYPE: "80"
    GTF_FILE: ""
    G_OPTION: "2"
    RNA_LIBRARY_TYPE: "fr-firststrand"

star:
    STAR_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/bin/"
    LIMIT_GENOME_GENERATE_RAM: "18000000000"
    GENOME_FASTA_FILE: "/bioinfo/users/jbrayet/Bureau/starAnnotations/Mus_musculus.GRCm38.dna.alt.fa"
    RUN_THREADN: "8"
    RUN_MODE: "genomeGenerate"
    GENOME_DIR: "/data/annotations/star_indexes/mm10"
    SJDB_GTF_FILE: "/bioinfo/users/jbrayet/Bureau/starAnnotations/Mus_musculus.GRCm38.84.gtf"
    SJDB_OVERHANG: "100"
    OUT_FILTER_MULTIMAP_NMAX: "2"
    READ_FILES_COMMAND: "zcat"
    QUANT_MODE: "GeneCounts"
    LB: "Illumina"

gatk:
    GATK_BIN_DIR: "/bioinfo/local/build/GATK/GenomeAnalysisTK-2.2-16-g9f648cb/"
    BED_FILE: ""
    FASTA_REFERENCE: "/bioinfo/users/jbrayet/Bureau/starAnnotations/Mus_musculus.GRCm38.dna.alt.fa"

samtools:
    SAMTOOLS_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/bin/"
    FASTA_REFERENCE: "/bioinfo/users/jbrayet/Bureau/starAnnotations/Mus_musculus.GRCm38.dna.alt.fa"

picard:
    MARKDUP: "yes"
    PICARD_TOOLS_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/bin/"

bedtools:
    BEDTOOLS_BIN_DIR: "~/miniconda3/envs/pipeline_rna_2/bin/"

curie_report:
    LIBRARY_DONE_BY: "Alban"
    SEQUENCING_DONE_BY: "Jocelyn"
    PROJECT_LEADER: "Jocelyn"
    RUN_DATE: "16-03-2016"
    SPECIES: "Mouse"
    SPECIES_BUILD: "mm9"
    READ_LENGTH: "100"
    MARKDUP: "yes"


